---
version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: waddlebot_db
    networks:
      - waddlebotnet
    volumes:
        - db_data:/var/lib/postgresql/data
  dbm:
    image: ghcr.io/penguincloud/waddledbm:main
    networks:
      - waddlebotnet
  chat:
    image: waddlebot-chat
    build: chat/
    networks:
        - waddlebotnet
  gateway:
    image: waddlebot-gateway
    build: gateway/
    networks:
      - waddlebotnet
    ports:
      - "8080:8080"

  listener:
    image: waddlebot-listener
    build: listener/
    networks:
      - waddlebotnet
    ports:
      - "6000:6000"
  marketplace:
    image: waddlebot-marketplace
    build: marketplace/
    networks:
      - waddlebotnet
    ports:
      - "7000:7000"
networks:
  waddlebotnet:
    driver: bridge

volumes:
  db_data:
