---
version: '3.8'

services:
  waddlebot:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: waddlebot_db
    networks:
      - waddlebot_network
    volumes:
        - db_data:/var/lib/postgresql/data
  dbm:
    image: penguincloud/waddledbm:latest
    networks:
      - waddlebot_network
  chat:
    image: waddlebot-chat:latest
    build: chat/
    networks:
        - waddlebot_network
  gateway:
    image: waddlebot-gateway:latest
    build: gateway/
    networks:
      - waddlebot_network
    ports:
      - "8080:8080"

  listener:
    image: waddlebot-listener:latest
    build: listener/
    networks:
      - waddlebot_network
    ports:
      - "6000:6000"
  marketplace:
    image: waddlebot-marketplace:latest
    build: marketplace/
    networks:
      - waddlebot_network
    ports:
      - "7000:7000"
networks:
  waddlebot_network:
    driver: bridge

volumes:
  db_data:
